# Generated by Django 5.2.17 on 2026-09-10 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубрика новостей',
                'verbose_name_plural': 'Рубрики новостей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO: title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO: description')),
                ('seo_h1', models.CharField(blank=True, max_length=255, verbose_name='SEO: H1')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og/', verbose_name='Картинка для соцсетей')),
                ('is_noindex', models.BooleanField(default=False, verbose_name='Закрыть от индексации')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(max_length=140, verbose_name='Slug')),
                ('url_path', models.CharField(editable=False, max_length=255, unique=True, verbose_name='Путь')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('menu_title', models.CharField(blank=True, max_length=120, verbose_name='Заголовок в меню')),
                ('template', models.CharField(default='pages/default.html', max_length=100, verbose_name='Шаблон')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(choices=[('header', 'Верхнее меню'), ('footer', 'Подвал'), ('mobile', 'Мобильное меню')], max_length=16, verbose_name='Расположение')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
                ('open_in_new', models.BooleanField(default=False, verbose_name='Открывать в новой вкладке')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('block_type', models.CharField(max_length=40, verbose_name='Тип блока')),
                ('payload', models.JSONField(default=dict, verbose_name='Содержимое')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='content.page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Блок страницы',
                'verbose_name_plural': 'Блоки страниц',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_phone', models.CharField(blank=True, max_length=40, verbose_name='Основной телефон')),
                ('main_email', models.EmailField(blank=True, max_length=254, verbose_name='Основная почта')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('work_hours', models.CharField(blank=True, max_length=255, verbose_name='График работы')),
                ('metrika_id', models.CharField(blank=True, max_length=20, verbose_name='ID Яндекс.Метрики')),
                ('verification_meta', models.TextField(blank=True, verbose_name='Мета-теги верификации')),
                ('socials', models.JSONField(blank=True, default=dict, verbose_name='Соцсети')),
                ('footer_text', models.TextField(blank=True, verbose_name='Текст в подвале')),
                ('privacy_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.page', verbose_name='Политика конфиденциальности')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO: title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO: description')),
                ('seo_h1', models.CharField(blank=True, max_length=255, verbose_name='SEO: H1')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og/', verbose_name='Картинка для соцсетей')),
                ('is_noindex', models.BooleanField(default=False, verbose_name='Закрыть от индексации')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('salary_note', models.CharField(blank=True, max_length=160, verbose_name='Зарплата')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='company.branch', verbose_name='Филиал')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='company.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-published_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO: title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO: description')),
                ('seo_h1', models.CharField(blank=True, max_length=255, verbose_name='SEO: H1')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og/', verbose_name='Картинка для соцсетей')),
                ('is_noindex', models.BooleanField(default=False, verbose_name='Закрыть от индексации')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('excerpt', models.TextField(blank=True, verbose_name='Анонс')),
                ('body', models.TextField(verbose_name='Текст')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/', verbose_name='Обложка')),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='content.newscategory', verbose_name='Рубрики')),
                ('machines', models.ManyToManyField(blank=True, related_name='news', to='catalog.machine', verbose_name='Техника')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-published_at', 'is_published'], name='news_feed_idx')],
            },
        ),
    ]
