# Generated by Django 5.2.17 on 2026-09-15 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_cataloglanding'),
        ('content', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('platform', models.CharField(choices=[('yandex', 'Яндекс Карты'), ('2gis', '2ГИС'), ('google', 'Google')], max_length=16, unique=True, verbose_name='Площадка')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Рейтинг')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Число оценок')),
                ('url', models.URLField(verbose_name='Ссылка на карточку')),
                ('widget_code', models.TextField(blank=True, help_text='Только для Яндекса: код виджета отзывов из Яндекс Карт. Он подтягивает отзывы сам и обновляет их каждые 72 часа.', verbose_name='Код виджета')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Показывать')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Данные на')),
            ],
            options={
                'verbose_name': 'Рейтинг на площадке',
                'verbose_name_plural': 'Рейтинги на площадках',
                'ordering': ['sort_order', 'platform'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='reviewsource_rating_in_range')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('author_name', models.CharField(max_length=160, verbose_name='Имя')),
                ('author_position', models.CharField(blank=True, max_length=160, verbose_name='Должность')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Компания')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=5, verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('source_note', models.CharField(blank=True, help_text='Например: «перенесён из 2ГИС с разрешения автора».', max_length=120, verbose_name='Откуда отзыв')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='catalog.machine', verbose_name='Техника')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-published_at', 'sort_order'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_in_range')],
            },
        ),
    ]
