# Generated by Django 5.2.17 on 2026-09-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_reviewsource_review'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reviewsource',
            name='reviewsource_rating_in_range',
        ),
        migrations.AlterField(
            model_name='reviewsource',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Для Google не заполняется: его оценку переносить на свой сайт нельзя.', max_digits=2, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='reviewsource',
            name='reviews_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Число оценок'),
        ),
        migrations.AddConstraint(
            model_name='reviewsource',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 0), ('rating__lte', 5)), _connector='OR'), name='reviewsource_rating_in_range'),
        ),
    ]
