# Generated by Django 5.2.17 on 2026-09-16 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_drop_google_review_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsource',
            name='logo',
            field=models.FileField(blank=True, help_text='Официальный логотип с сайта площадки, SVG или PNG. Если не загружен, показывается название текстом.', upload_to='review-sources/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'webp'])], verbose_name='Логотип площадки'),
        ),
    ]
