# Generated by Django 5.2.17 on 2026-09-10 04:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('price', 'Запрос цены'), ('selection', 'Подбор техники'), ('service', 'Заявка в сервис'), ('parts', 'Запрос запчастей'), ('callback', 'Обратный звонок'), ('tco', 'Калькулятор стоимости владения'), ('vacancy', 'Отклик на вакансию')], db_index=True, max_length=20, verbose_name='Тип')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Обработана'), ('spam', 'Спам')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('name', models.CharField(max_length=160, verbose_name='Имя')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Компания')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='Страница отправки')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='Источник перехода')),
                ('utm', models.JSONField(blank=True, default=dict, verbose_name='UTM-метки')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('consent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия')),
                ('purge_after', models.DateField(blank=True, db_index=True, null=True, verbose_name='Хранить до')),
                ('is_anonymized', models.BooleanField(default=False, verbose_name='Обезличена')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработана')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Создана'), ('status_changed', 'Статус изменён'), ('comment', 'Комментарий'), ('email_sent', 'Письмо отправлено'), ('email_failed', 'Письмо не отправлено'), ('anonymized', 'Обезличена')], max_length=40, verbose_name='Событие')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
            ],
            options={
                'verbose_name': 'Событие заявки',
                'verbose_name_plural': 'События заявок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('lead_type', models.CharField(blank=True, choices=[('price', 'Запрос цены'), ('selection', 'Подбор техники'), ('service', 'Заявка в сервис'), ('parts', 'Запрос запчастей'), ('callback', 'Обратный звонок'), ('tco', 'Калькулятор стоимости владения'), ('vacancy', 'Отклик на вакансию')], help_text='Пусто — правило подходит для любого типа заявки.', max_length=20, verbose_name='Тип заявки')),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), default=list, size=None, verbose_name='Адреса')),
                ('priority', models.PositiveSmallIntegerField(default=100, verbose_name='Приоритет')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Правило маршрутизации',
                'verbose_name_plural': 'Правила маршрутизации заявок',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConsentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, verbose_name='Код')),
                ('version', models.CharField(max_length=20, verbose_name='Версия')),
                ('text', models.TextField(verbose_name='Текст согласия')),
                ('published_at', models.DateTimeField(verbose_name='Опубликовано')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующая')),
            ],
            options={
                'verbose_name': 'Версия согласия',
                'verbose_name_plural': 'Версии согласия на обработку ПДн',
                'ordering': ['-published_at'],
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='consentversion_unique_version')],
            },
        ),
    ]
