# Generated by Django 5.2.17 on 2026-09-10 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('company', '0001_initial'),
        ('leads', '0001_initial'),
        ('parts', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='lead',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='company.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='lead',
            name='consent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.consentversion', verbose_name='Согласие'),
        ),
        migrations.AddField(
            model_name='lead',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='company.department', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='lead',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalog.machine', verbose_name='Техника'),
        ),
        migrations.AddField(
            model_name='lead',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='parts.part', verbose_name='Запчасть'),
        ),
        migrations.AddField(
            model_name='lead',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='services.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='leadevent',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='leadevent',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='leads.lead', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='leadroutingrule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='catalog.category', verbose_name='Категория техники'),
        ),
        migrations.AddField(
            model_name='leadroutingrule',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_rules', to='company.department', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='leadroutingrule',
            name='machine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='catalog.machinetype', verbose_name='Тип техники'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', '-created_at'], name='lead_status_idx'),
        ),
    ]
