# Generated by Django 5.2.17 on 2026-09-10 05:29

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='referrer',
            field=apps.core.fields.URLField(blank=True, max_length=500, verbose_name='Источник перехода'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_url',
            field=apps.core.fields.URLField(blank=True, max_length=500, verbose_name='Страница отправки'),
        ),
    ]
