# Generated by Django 5.2.17 on 2026-09-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_referrer_alter_lead_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='type',
            field=models.CharField(choices=[('price', 'Запрос цены'), ('selection', 'Подбор техники'), ('service', 'Заявка в сервис'), ('parts', 'Запрос запчастей'), ('callback', 'Обратный звонок'), ('tco', 'Калькулятор стоимости владения'), ('leasing', 'Заявка на лизинг'), ('vacancy', 'Отклик на вакансию')], db_index=True, max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='leadroutingrule',
            name='lead_type',
            field=models.CharField(blank=True, choices=[('price', 'Запрос цены'), ('selection', 'Подбор техники'), ('service', 'Заявка в сервис'), ('parts', 'Запрос запчастей'), ('callback', 'Обратный звонок'), ('tco', 'Калькулятор стоимости владения'), ('leasing', 'Заявка на лизинг'), ('vacancy', 'Отклик на вакансию')], help_text='Пусто — правило подходит для любого типа заявки.', max_length=20, verbose_name='Тип заявки'),
        ),
    ]
