# Generated by Django 5.2.17 on 2026-09-15 16:17

import apps.leads.storage
import apps.leads.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_type_alter_leadroutingrule_lead_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=apps.leads.storage.PrivateFileSystemStorage(), upload_to=apps.leads.storage.attachment_upload_to, validators=[apps.leads.validators.LeadFileValidator()], verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Исходное имя')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Размер, байт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='leads.lead', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['id'],
            },
        ),
    ]
