# Generated by Django 5.2.17 on 2026-09-14 13:53

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('company', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='receives_lead_emails',
            field=models.BooleanField(default=False, help_text='Сотрудник будет получать письма о новых заявках. Если указан отдел, придут только заявки этого отдела; без отдела — все.', verbose_name='Получать заявки на почту'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('receives_lead_emails', False), models.Q(('email', ''), _negated=True), _connector='OR'), name='user_lead_recipient_needs_email'),
        ),
    ]
