# Generated by Django 5.2.17 on 2026-09-10 04:35

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_postgres_extensions"),
        ('catalog', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO: title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO: description')),
                ('seo_h1', models.CharField(blank=True, max_length=255, verbose_name='SEO: H1')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og/', verbose_name='Картинка для соцсетей')),
                ('is_noindex', models.BooleanField(default=False, verbose_name='Закрыть от индексации')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория запчастей',
                'verbose_name_plural': 'Категории запчастей',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('article', models.CharField(max_length=64, verbose_name='Артикул')),
                ('article_norm', models.CharField(db_index=True, max_length=64, verbose_name='Артикул (нормализованный)')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_original', models.BooleanField(default=True, verbose_name='Оригинальная')),
                ('unit', models.CharField(default='шт', max_length=16, verbose_name='Единица')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Вес, кг')),
                ('image', models.ImageField(blank=True, null=True, upload_to='parts/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Ключ 1С')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='catalog.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='parts.partcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_stock', 'В наличии'), ('low', 'Мало'), ('on_order', 'Под заказ'), ('none', 'Нет')], default='none', max_length=16, verbose_name='Статус')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество')),
                ('lead_time', models.CharField(blank=True, max_length=120, verbose_name='Срок поставки')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Синхронизировано')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='company.branch', verbose_name='Филиал')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='parts.part', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Наличие запчасти',
                'verbose_name_plural': 'Наличие запчастей',
            },
        ),
        migrations.CreateModel(
            name='PartAnalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('analog', 'Аналог'), ('replacement', 'Заменён на')], default='analog', max_length=16, verbose_name='Тип')),
                ('analog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_for', to='parts.part', verbose_name='Аналог')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analogs', to='parts.part', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Аналог',
                'verbose_name_plural': 'Аналоги',
                'constraints': [models.UniqueConstraint(fields=('part', 'analog'), name='partanalog_unique'), models.CheckConstraint(condition=models.Q(('part', models.F('analog')), _negated=True), name='partanalog_not_self')],
            },
        ),
        migrations.CreateModel(
            name='PartApplicability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='catalog.machine', verbose_name='Техника')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicability', to='parts.part', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Применимость',
                'verbose_name_plural': 'Применимость',
                'constraints': [models.UniqueConstraint(fields=('part', 'machine'), name='partapplicability_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='part',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='part_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='part',
            index=django.contrib.postgres.indexes.GinIndex(fields=['article_norm'], name='part_article_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('brand', 'article'), name='part_unique_article'),
        ),
        migrations.AddConstraint(
            model_name='partstock',
            constraint=models.UniqueConstraint(fields=('part', 'branch'), name='partstock_unique_branch'),
        ),
    ]
