# Generated by Django 5.2.17 on 2026-09-10 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO: title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO: description')),
                ('seo_h1', models.CharField(blank=True, max_length=255, verbose_name='SEO: H1')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og/', verbose_name='Картинка для соцсетей')),
                ('is_noindex', models.BooleanField(default=False, verbose_name='Закрыть от индексации')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('city', models.CharField(max_length=120, verbose_name='Город')),
                ('is_head_office', models.BooleanField(default=False, verbose_name='Головной офис')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('postcode', models.CharField(blank=True, max_length=10, verbose_name='Индекс')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('timezone', models.CharField(default='Asia/Vladivostok', max_length=40, verbose_name='Часовой пояс')),
                ('work_hours', models.CharField(blank=True, max_length=255, verbose_name='График работы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['sort_order', 'city'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('full_name', models.CharField(max_length=160, verbose_name='ФИО')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/', verbose_name='Фото')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.branch', verbose_name='Филиал')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='company.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['sort_order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('kind', models.CharField(choices=[('phone', 'Телефон'), ('mobile', 'Мобильный'), ('email', 'E-mail'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=16, verbose_name='Тип')),
                ('value', models.CharField(max_length=120, verbose_name='Значение')),
                ('extension', models.CharField(blank=True, max_length=16, verbose_name='Добавочный')),
                ('label', models.CharField(blank=True, max_length=80, verbose_name='Подпись')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='company.branch', verbose_name='Филиал')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='company.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('branch__isnull', False), ('employee__isnull', True)), models.Q(('branch__isnull', True), ('employee__isnull', False)), _connector='OR'), name='contactpoint_owner_required')],
            },
        ),
    ]
