# Generated by Django 5.2.17 on 2026-09-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('lead_time', models.CharField(blank=True, max_length=120, verbose_name='Срок')),
                ('note', models.CharField(blank=True, help_text='Например: «до портов Ванино и Советская Гавань».', max_length=200, verbose_name='Примечание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Способ доставки',
                'verbose_name_plural': 'Доставка',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
