# Generated by Django 5.2.17 on 2026-09-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotFoundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=500, unique=True, verbose_name='Путь')),
                ('referrer', models.CharField(blank=True, max_length=500, verbose_name='Источник перехода')),
                ('hits', models.PositiveIntegerField(default=1, verbose_name='Обращений')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Впервые')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Последний раз')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Ненайденный адрес',
                'verbose_name_plural': 'Ненайденные адреса (404)',
                'ordering': ['-hits', '-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(db_index=True, max_length=500, unique=True, verbose_name='Старый путь')),
                ('new_path', models.CharField(max_length=500, verbose_name='Новый путь')),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, '301 — постоянный'), (302, '302 — временный')], default=301, verbose_name='Код ответа')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('is_auto', models.BooleanField(default=False, verbose_name='Создано автоматически')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='Срабатываний')),
                ('last_hit_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее срабатывание')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Редирект',
                'verbose_name_plural': 'Редиректы',
                'ordering': ['-hits', 'old_path'],
            },
        ),
    ]
