# Generated by Django 5.2.17 on 2026-09-10 04:35

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа характеристик',
                'verbose_name_plural': 'Группы характеристик',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpecKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name='Единица измерения')),
                ('value_type', models.CharField(choices=[('number', 'Число'), ('string', 'Строка'), ('bool', 'Да/Нет'), ('option', 'Значение из списка')], default='number', max_length=10, verbose_name='Тип значения')),
                ('is_filterable', models.BooleanField(db_index=True, default=False, verbose_name='Участвует в фильтрах')),
                ('is_in_card', models.BooleanField(default=False, verbose_name='Выводить в плитке каталога')),
                ('is_comparable', models.BooleanField(default=True, verbose_name='Участвует в сравнении')),
                ('decimals', models.PositiveSmallIntegerField(default=0, verbose_name='Знаков после запятой')),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=160), blank=True, default=list, size=None, verbose_name='Синонимы')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keys', to='specs.specgroup', verbose_name='Группа')),
                ('machine_types', models.ManyToManyField(blank=True, related_name='spec_keys', to='catalog.machinetype', verbose_name='Типы техники')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Справочник параметров',
                'ordering': ['group__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpecOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('code', models.SlugField(max_length=60, verbose_name='Код')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('spec_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='specs.speckey', verbose_name='Параметр')),
            ],
            options={
                'verbose_name': 'Значение параметра',
                'verbose_name_plural': 'Значения параметров',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MachineSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_num', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Число')),
                ('value_str', models.CharField(blank=True, max_length=255, verbose_name='Строка')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='Да/Нет')),
                ('value_num_max', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Число, верхняя граница')),
                ('raw_value', models.CharField(blank=True, max_length=255, verbose_name='Исходное значение')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='catalog.machine', verbose_name='Техника')),
                ('spec_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='specs.speckey', verbose_name='Параметр')),
                ('value_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='specs.specoption', verbose_name='Значение из списка')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['spec_key__group__sort_order', 'spec_key__sort_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='specoption',
            constraint=models.UniqueConstraint(fields=('spec_key', 'code'), name='specoption_unique_code'),
        ),
        migrations.AddIndex(
            model_name='machinespec',
            index=models.Index(fields=['spec_key', 'value_num'], name='spec_num_filter_idx'),
        ),
        migrations.AddIndex(
            model_name='machinespec',
            index=models.Index(fields=['spec_key', 'value_option'], name='spec_opt_filter_idx'),
        ),
        migrations.AddConstraint(
            model_name='machinespec',
            constraint=models.UniqueConstraint(fields=('machine', 'spec_key'), name='machinespec_unique_key'),
        ),
        migrations.AddConstraint(
            model_name='machinespec',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('value_bool__isnull', True), ('value_num__isnull', False), ('value_option__isnull', True), ('value_str', '')), models.Q(('value_bool__isnull', True), ('value_num__isnull', True), ('value_num_max__isnull', True), ('value_option__isnull', True), models.Q(('value_str', ''), _negated=True)), models.Q(('value_bool__isnull', False), ('value_num__isnull', True), ('value_num_max__isnull', True), ('value_option__isnull', True), ('value_str', '')), models.Q(('value_bool__isnull', True), ('value_num__isnull', True), ('value_num_max__isnull', True), ('value_option__isnull', False), ('value_str', '')), _connector='OR'), name='machinespec_exactly_one_value'),
        ),
        migrations.AddConstraint(
            model_name='machinespec',
            constraint=models.CheckConstraint(condition=models.Q(('value_num_max__isnull', True), models.Q(('value_num__isnull', False), ('value_num_max__gte', models.F('value_num'))), _connector='OR'), name='machinespec_range_ordered'),
        ),
    ]
