# Generated by Django 5.2.17 on 2026-09-10 04:35

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO: title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO: description')),
                ('seo_h1', models.CharField(blank=True, max_length=255, verbose_name='SEO: H1')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og/', verbose_name='Картинка для соцсетей')),
                ('is_noindex', models.BooleanField(default=False, verbose_name='Закрыть от индексации')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Логотип')),
                ('logo_hover', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Логотип при наведении')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO: title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO: description')),
                ('seo_h1', models.CharField(blank=True, max_length=255, verbose_name='SEO: H1')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og/', verbose_name='Картинка для соцсетей')),
                ('is_noindex', models.BooleanField(default=False, verbose_name='Закрыть от индексации')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Картинка')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория техники',
                'verbose_name_plural': 'Категории техники',
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('name_plural', models.CharField(max_length=120, verbose_name='Название во множественном числе')),
                ('icon', models.FileField(blank=True, null=True, upload_to='types/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Тип техники',
                'verbose_name_plural': 'Типы техники',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO: title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO: description')),
                ('seo_h1', models.CharField(blank=True, max_length=255, verbose_name='SEO: H1')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og/', verbose_name='Картинка для соцсетей')),
                ('is_noindex', models.BooleanField(default=False, verbose_name='Закрыть от индексации')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=180, verbose_name='Название')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Полное название')),
                ('series', models.CharField(blank=True, max_length=80, verbose_name='Серия')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('equipment', models.TextField(blank=True, verbose_name='Комплектация')),
                ('warranty_note', models.CharField(blank=True, max_length=160, verbose_name='Гарантия')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Цена')),
                ('price_note', models.CharField(blank=True, max_length=160, verbose_name='Примечание к цене')),
                ('is_price_on_request', models.BooleanField(default=True, verbose_name='Цена по запросу')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая')),
                ('specs_cache', models.JSONField(blank=True, default=dict, verbose_name='Снимок характеристик')),
                ('raw_specs', models.JSONField(blank=True, default=dict, verbose_name='Сырые характеристики')),
                ('source_url', models.URLField(blank=True, verbose_name='Источник')),
                ('source_hash', models.CharField(blank=True, max_length=64, verbose_name='Хеш источника')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='catalog.brand', verbose_name='Бренд')),
                ('categories', models.ManyToManyField(blank=True, related_name='machines', to='catalog.category', verbose_name='Категории')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='catalog.machinetype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Каталог техники',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MachineDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('kind', models.CharField(choices=[('brochure', 'Брошюра'), ('spec', 'Техническая спецификация'), ('certificate', 'Сертификат'), ('manual', 'Руководство')], default='brochure', max_length=20, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='docs/%Y/', verbose_name='Файл')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер, байт')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.machine', verbose_name='Техника')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MachineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('image', models.ImageField(upload_to='machines/%Y/%m/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Альтернативный текст')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.machine', verbose_name='Техника')),
            ],
            options={
                'verbose_name': 'Изображение техники',
                'verbose_name_plural': 'Изображения техники',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('machine',), name='one_main_image_per_machine')],
            },
        ),
        migrations.CreateModel(
            name='MachineStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_stock', 'В наличии'), ('low', 'Мало'), ('on_order', 'Под заказ'), ('none', 'Нет')], default='none', max_length=16, verbose_name='Статус')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество')),
                ('lead_time', models.CharField(blank=True, max_length=120, verbose_name='Срок готовности')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Синхронизировано')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_stocks', to='company.branch', verbose_name='Филиал')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.machine', verbose_name='Техника')),
            ],
            options={
                'verbose_name': 'Наличие техники',
                'verbose_name_plural': 'Наличие техники',
                'constraints': [models.UniqueConstraint(fields=('machine', 'branch'), name='machinestock_unique_branch')],
            },
        ),
        migrations.AddIndex(
            model_name='machine',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='machine_search_gin'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=django.contrib.postgres.indexes.GinIndex(fields=['specs_cache'], name='machine_specs_gin', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['brand', 'machine_type'], name='machine_brand_type_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(condition=models.Q(('is_active', True), ('is_published', True)), fields=['is_active', 'is_published'], name='machine_visible_idx'),
        ),
    ]
