# Generated by Django 5.2.17 on 2026-09-10 05:29

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='source_url',
            field=apps.core.fields.URLField(blank=True, verbose_name='Источник'),
        ),
    ]
