# Generated by Django 5.2.17 on 2026-09-10 20:43

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # Индексы gin_trgm_ops не создадутся без установленного расширения.
        # Без этой зависимости порядок миграций на чистой базе не гарантирован,
        # и развёртывание с нуля падает — при этом на уже существующей базе,
        # где расширение установлено, всё проходит.
        ("core", "0001_postgres_extensions"),
        ('catalog', '0002_alter_machine_source_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='machine',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='machine_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=django.contrib.postgres.indexes.GinIndex(fields=['full_name'], name='machine_fullname_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
