# Generated by Django 5.2.17 on 2026-09-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_machine_machine_name_trgm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineimage',
            name='image_webp',
            field=models.ImageField(blank=True, editable=False, upload_to='machines/%Y/%m/webp/', verbose_name='Копия в WebP'),
        ),
        migrations.AddField(
            model_name='machineimage',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='machines/%Y/%m/thumb/', verbose_name='Превью'),
        ),
    ]
