# Generated by Django 5.2.17 on 2026-09-10 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_machineimage_image_webp_machineimage_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO: title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO: description')),
                ('seo_h1', models.CharField(blank=True, max_length=255, verbose_name='SEO: H1')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og/', verbose_name='Картинка для соцсетей')),
                ('is_noindex', models.BooleanField(default=False, verbose_name='Закрыть от индексации')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('intro', models.TextField(blank=True, help_text='Уникальный текст под запрос. Копировать описания с корпоративного сайта нельзя — это прямые дубли на одном домене.', verbose_name='Вступительный текст')),
                ('is_featured', models.BooleanField(default=True, help_text='Ссылка на подборку выводится под списком техники: внутренняя перелинковка помогает индексации.', verbose_name='Показывать в каталоге')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landings', to='catalog.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landings', to='catalog.category', verbose_name='Категория')),
                ('machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landings', to='catalog.machinetype', verbose_name='Тип техники')),
            ],
            options={
                'verbose_name': 'Подборка каталога',
                'verbose_name_plural': 'Подборки каталога',
                'ordering': ['sort_order', 'title'],
                'constraints': [models.CheckConstraint(condition=models.Q(('brand__isnull', False), ('machine_type__isnull', False), ('category__isnull', False), _connector='OR'), name='cataloglanding_has_condition')],
            },
        ),
    ]
