# Generated by Django 5.2.17 on 2026-09-15 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_cataloglanding'),
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogLandingSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_min', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='От')),
                ('value_max', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='До')),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_conditions', to='catalog.cataloglanding', verbose_name='Подборка')),
                ('spec_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_conditions', to='specs.speckey', verbose_name='Параметр')),
            ],
            options={
                'verbose_name': 'Условие по характеристике',
                'verbose_name_plural': 'Условия по характеристикам',
                'ordering': ['spec_key__sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('landing', 'spec_key'), name='cataloglandingspec_unique_key'), models.CheckConstraint(condition=models.Q(('value_min__isnull', False), ('value_max__isnull', False), _connector='OR'), name='cataloglandingspec_has_bound'), models.CheckConstraint(condition=models.Q(('value_min__isnull', True), ('value_max__isnull', True), ('value_max__gte', models.F('value_min')), _connector='OR'), name='cataloglandingspec_range_ordered')],
            },
        ),
    ]
