# Generated by Django 5.2.17 on 2026-09-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeasingPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Логотип')),
                ('url', models.URLField(blank=True, verbose_name='Сайт')),
                ('note', models.CharField(blank=True, help_text='Например: «спецпрограмма на технику Komatsu».', max_length=200, verbose_name='Примечание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Партнёр по финансированию',
                'verbose_name_plural': 'Партнёры по финансированию',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeasingTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_advance_percent', models.PositiveSmallIntegerField(default=10, verbose_name='Аванс от, %')),
                ('max_advance_percent', models.PositiveSmallIntegerField(default=49, verbose_name='Аванс до, %')),
                ('min_months', models.PositiveSmallIntegerField(default=12, verbose_name='Срок от, месяцев')),
                ('max_months', models.PositiveSmallIntegerField(default=60, verbose_name='Срок до, месяцев')),
                ('default_markup_percent', models.DecimalField(decimal_places=2, default=7, help_text='Ориентир для калькулятора. Точную ставку называет лизинговая компания после рассмотрения заявки.', max_digits=5, verbose_name='Удорожание по умолчанию, % в год')),
                ('decision_days', models.CharField(default='1–3 дня', max_length=60, verbose_name='Срок решения')),
                ('intro', models.TextField(blank=True, verbose_name='Текст раздела')),
                ('is_credit_available', models.BooleanField(default=True, verbose_name='Доступен кредит')),
            ],
            options={
                'verbose_name': 'Условия финансирования',
                'verbose_name_plural': 'Условия финансирования',
                'constraints': [models.CheckConstraint(condition=models.Q(('max_advance_percent__gte', models.F('min_advance_percent'))), name='leasingterms_advance_range_ordered'), models.CheckConstraint(condition=models.Q(('max_months__gte', models.F('min_months'))), name='leasingterms_months_range_ordered')],
            },
        ),
    ]
