# Generated by Django 5.2.17 on 2026-09-15 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasingterms',
            name='max_months',
            field=models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Срок до, месяцев'),
        ),
        migrations.AlterField(
            model_name='leasingterms',
            name='min_months',
            field=models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Срок от, месяцев'),
        ),
        migrations.AddConstraint(
            model_name='leasingterms',
            constraint=models.CheckConstraint(condition=models.Q(('min_months__gte', 1)), name='leasingterms_months_positive'),
        ),
    ]
