# Generated by Django 5.2.17 on 2026-09-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40, verbose_name='Источник')),
                ('kind', models.CharField(max_length=40, verbose_name='Что импортировали')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='running', max_length=16, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('stats', models.JSONField(default=dict, verbose_name='Статистика')),
                ('log', models.TextField(blank=True, verbose_name='Журнал')),
            ],
            options={
                'verbose_name': 'Прогон импорта',
                'verbose_name_plural': 'Прогоны импорта',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SourcePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='Адрес')),
                ('path', models.CharField(db_index=True, max_length=500, verbose_name='Путь')),
                ('http_status', models.PositiveSmallIntegerField(default=200, verbose_name='Код ответа')),
                ('page_type', models.CharField(blank=True, choices=[('machine', 'Карточка техники'), ('catalog', 'Раздел каталога'), ('part', 'Запчасти'), ('content', 'Текстовая страница'), ('news', 'Новость'), ('contacts', 'Контакты'), ('junk', 'Не переносим')], max_length=20, verbose_name='Тип страницы')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('content_hash', models.CharField(blank=True, max_length=64, verbose_name='Хеш содержимого')),
                ('fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='Загружено')),
                ('raw_path', models.CharField(blank=True, max_length=500, verbose_name='Путь к кэшу HTML')),
                ('is_migrated', models.BooleanField(db_index=True, default=False, verbose_name='Перенесено')),
                ('target_path', models.CharField(blank=True, max_length=500, verbose_name='Новый путь')),
            ],
            options={
                'verbose_name': 'Страница источника',
                'verbose_name_plural': 'Страницы источника',
                'ordering': ['path'],
            },
        ),
    ]
