# Generated by Django 5.2.17 on 2026-09-10 05:29

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcepage',
            name='url',
            field=apps.core.fields.URLField(max_length=500, unique=True, verbose_name='Адрес'),
        ),
    ]
